### PR TITLE
Add README.md

### PR DESCRIPTION
**Pull request by rubenchazarra**
Add Documentation file

### CODE REVIEW

**Comment by pinin4fjords** [comment]
Thanks @rubenchazarra ! Could you just split commands by line where you've copied them from the .bats file? This will be wherever there's a backslash, as you've done for the 'Get feature space' one. 

I'll let @a-solovyev12 do the sign-off though, since it's his code.

**Review by a-solovyev12 — APPROVED** [review]
Thanks @rubenchazarra! Looks good to me, you can merge after you make changes as per Jon's comment and resolve conflicts.

**Comment by pinin4fjords** [comment]
@rubenchazarra Don't forget to make the tweaks requested above to this one too, and then you can squash and merge.

**Comment by rubenchazarra** [comment]
New branch was created. PR will be done with this new branch.

**Pull request closed without merging**
