### PR TITLE
CLI compatibility with scPred=1.9.0

### PR DESCRIPTION
**Pull request by a-solovyev12**
- A major update of [scPred](https://github.com/powellgenomicslab/scPred) has been released, so the CLI wrapper needs to be adapted accordingly
- scPred is now working under the Seurat framework, therefore processing steps have been removed. Normalisation/scaling will now be carried out using `r-seurat-scripts`. 
- some methods have been added/modified/removed

### CODE REVIEW

**Comment by pinin4fjords** [comment]
I see a 'reduction' parameter at https://github.com/powellgenomicslab/scPred/blob/32bc593e3a6f5c1584ff8f3497aa09039c50fda6/R/getFeatureSpace.R#L39 you're missing in scpred_get_feature_space.R

**Comment by pinin4fjords** [comment]
Could you also add the new parameters from https://github.com/powellgenomicslab/scPred/blob/master/R/scPredict.R to the predict script?

**Comment by pinin4fjords** [comment]
And similarly match up with the parameters of the training function?

**Review by pinin4fjords — APPROVED** [review]
Okay, looking good now, thanks for addressing the comments.

**Comment by a-solovyev12** [comment]
Thanks for review @pinin4fjords.

**Pull request merged**
