### PR TITLE
sce object processing

### PR DESCRIPTION
**Pull request by a-solovyev12**
This PR adds a pre-processing step for sce object which extracts 'un-sparsed' expression matrix and metadata, if specified. The `scpred-eigen-decompose.R` method accepts a matrix object in text format, so it has to be converted from the 10X-like sparse matrix in SCE object. This step is run in case no train/test splitting is required and the model is trained to obtain predictions for new data, not for model performance evaluation.

### CODE REVIEW

**Comment by pinin4fjords** [comment]
Thanks @a-solovyev12 . Could you expand a bit further in the description as to why the unsparsing is required?

**Comment by a-solovyev12** [comment]
@pinin4fjords Thanks for review. The tool accepts a matrix in text format, so it has to be converted from the sparse matrix in SCE object.

**Comment by pinin4fjords** [comment]
> @pinin4fjords Thanks for review. The tool accepts a matrix in text format, so it has to be converted from the sparse matrix in SCE object.

Could you be more specific? Which method specifically requires unsparsed matrices?

**Comment by a-solovyev12** [comment]
@pinin4fjords it is the `scpred-eigen-decompose.R` script - runs eigenvalue decomposition of the expression matrix.

**Comment by pinin4fjords** [comment]
What I was looking for was to understand the bit of code where from where the requirement originates. I hunted it down myself:

https://github.com/IMB-Computational-Genomics-Lab/scPred/blob/21a31682b5e14950ef414e3b4699d4eec4506543/R/eigenDecompose.R#L44

It's a real shame when these methods require unsparsing, but never mind! Seems sensible.

**Review by pinin4fjords — APPROVED** [review]

**Pull request merged**
